def unnamed():
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  set_tool_communication(False, 115200, 0, 1, 1.5, 3.5)
  set_tool_output_mode(0)
  set_tool_digital_output_mode(0, 1)
  set_tool_digital_output_mode(1, 1)
  set_tool_voltage(0)
  set_safety_mode_transition_hardness(1)
  step_count_0fd5c70b_8a5b_40e3_810e_adc5b5f9080a = 0
  thread Step_Counter_Thread_86173daf_8cc8_4173_a85c_5202322ab25c():
    while (True):
      step_count_0fd5c70b_8a5b_40e3_810e_adc5b5f9080a = step_count_0fd5c70b_8a5b_40e3_810e_adc5b5f9080a + 1
      sync()
    end
  end
  run Step_Counter_Thread_86173daf_8cc8_4173_a85c_5202322ab25c()
  set_gravity([0.0, -1.2026031567627009E-15, -9.82])
  set_tcp(p[0.0,0.0,0.0,0.0,0.0,0.0])
  set_payload(0.0)
  while (True):
    $ 1 "Robot Program"
    $ 2 "Script: exercise_5.script"
    dncsnvwsnovkds
  end
end
